export const playersData = [
	{
		id: 1,
		img: 'images/abu_jayed.png',
		fullName: 'Abu Jayed Chowdhury',
		born: 'August 02, 1993',
		age: '28y 17d',
		battingStyle: 'Right hand bat',
		bowlingStyle: 'Right arm fast medium',
		playRole: 'Bower',
		teams: 'Bangladesh',
		salary: 45000,
		inListed: false,
	},
	{
		id: 2,
		img: 'images/hasan_mahmud.png',
		fullName: 'Hasan Mahmud',
		born: 'October 12, 1999,',
		age: '21y 311d',
		battingStyle: 'Right hand bat',
		bowlingStyle: 'Right arm fast medium',
		playRole: 'Bower',
		teams: 'Bangladesh',
		salary: 48000,
		inListed: false,
	},
	{
		id: 3,
		img: 'images/afif_hasan.png',
		fullName: 'Afif Hossain Dhrubo',
		born: 'September 22, 1999',
		age: '21y 311d',
		battingStyle: 'Left hand bat',
		bowlingStyle: 'Right arm offbreak',
		playRole: 'Allrounder',
		teams: 'Bangladesh',
		salary: 50000,
		inListed: false,
	},
	{
		id: 4,
		img: 'images/ebadot_hussain.png',
		fullName: 'Ebadot Hossain Chowdhury',
		born: 'January 07, 1994',
		age: '27y 224d',
		battingStyle: 'Right hand bat',
		bowlingStyle: 'Right arm fast medium',
		playRole: 'Bowler',
		teams: 'Bangladesh',
		salary: 48000,
		inListed: false,
	},
	{
		id: 5,
		img: 'images/liton_das.png',
		fullName: 'Liton Kumar Das',
		born: 'October 13, 1994',
		age: '26y 310d',
		battingStyle: 'Right hand bat',
		bowlingStyle: 'Right arm fast medium',
		playRole: 'Wicketkeeper batter',
		teams: 'Bangladesh',
		salary: 49000,
		inListed: false,
	},
	{
		id: 6,
		img: 'images/mahedi_hasan.png',
		fullName: 'Mahedi Hasan',
		born: 'December 12, 1994',
		age: '26y 250d',
		battingStyle: 'Right hand bat',
		bowlingStyle: 'Right arm offbreak',
		playRole: 'Top order batter',
		teams: 'Bangladesh',
		salary: 49000,
		inListed: false,
	},
	{
		id: 7,
		img: 'images/mohammad_mahmudullah.png',
		fullName: 'Mohammad Mahmudullah',
		born: 'February 04, 1986',
		age: '35y 196d',
		battingStyle: 'Right hand bat',
		bowlingStyle: 'Right arm offbreak',
		playRole: 'Allrounder',
		teams: 'Bangladesh',
		salary: 50000,
		inListed: false,
	},
	{
		id: 8,
		img: 'images/mithun.png',
		fullName: 'Mohammad Mithun',
		born: 'March 02, 1991',
		age: '30y 170d',
		battingStyle: 'Right hand bat',
		bowlingStyle: 'Right arm offbreak',
		playRole: 'Top order batter',
		teams: 'Bangladesh',
		salary: 50000,
		inListed: false,
	},
	{
		id: 9,
		img: 'images/naim_sheikh.png',
		fullName: 'Mohammad Naim Sheikh',
		born: 'August 22, 1999',
		age: '21y 362d',
		battingStyle: 'Left hand bat',
		bowlingStyle: 'Right arm offbreak',
		playRole: 'Opening batter',
		teams: 'Bangladesh',
		salary: 45000,
		inListed: false,
	},
	{
		id: 10,
		img: 'images/saifuddin.png',
		fullName: 'Mohammad Saifuddin',
		born: 'November 01, 1996',
		age: '24y 291d',
		battingStyle: 'Left hand bat',
		bowlingStyle: 'Right arm medium fast',
		playRole: 'Bowling allrounder',
		teams: 'Bangladesh',
		salary: 48000,
		inListed: false,
	},
	{
		id: 11,
		img: 'images/mominul.png',
		fullName: 'Mominul Haque',
		born: 'September 29, 1991',
		age: '29y 324d',
		battingStyle: 'Left hand bat',
		bowlingStyle: 'Slow left arm orthodox',
		playRole: 'Middle order batter',
		teams: 'Bangladesh',
		salary: 48000,
		inListed: false,
	},
	{
		id: 12,
		img: 'images/taskin.png',
		fullName: 'Taskin Ahmed',
		born: 'April 03, 1995',
		age: '26y 138d',
		battingStyle: 'Left hand bat',
		bowlingStyle: 'Right arm fast',
		playRole: 'Bowler',
		teams: 'Bangladesh',
		salary: 42000,
		inListed: false,
	},
];
